### PR TITLE
Revert removal of get_rcode

### LINKED ISSUE #827: Revert the removal of deprecated functions
During integration test for release prep, we got warning when running R CMD Check on last stable version (0.8.14) of tmc:

```r
* checking dependencies in R code ... WARNING
Missing or unexported objects:
  ‘teal::get_rcode_srv’ ‘teal::get_rcode_ui’
```

We removed these deprecated functions from the codebase with this [PR].(https://github.com/insightsengineering/teal/pull/819).
Because `tmc` is not being released, we need to restore these functions back.

Update: We see the same error with `tmg`, `teal.osprey`, and `teal.goshawk`

### Acceptance Criteria
* Restore the deprecated functions by reverting the changes/removal in
  * get_rcode.R
  * get_rcode_utils.R
  * test-get_rcode.R
* Run R CMD Check on updated teal and tmc, tmg, teal.osprey, and teal.goshawk
  * For tmc, make sure to checkout from 0.8.14 version before running R CMD Check. You can run `git checkout tags/v0.8.14`
  * Do the same for the rest of packages

### PR DESCRIPTION
**Pull request by asbates**
We need to put `get_rcode` and associated functions back because `teal.modules.clinical` is still using it.

Fixes #827

### CODE REVIEW

**Comment by asbates** [comment]
@donyunardi I've ran R CMD check on this PR and all good. 

I also ran on tmc 0.8.14 but I'm having an issue that is unrelated to the changes here and I'm not sure how to resolve. Some tests are complaining that I don't have any archive versions of `scda` installed. But I don't know which one is needed. Also, I can run the flagged code and the tests fine if I run them manually.

image

**Comment by donyunardi** [comment]
@asbates 
You need to install `scda` and `scda.2022`:
```r
remotes::install_github("insightsengineering/scda")
remotes::install_github("insightsengineering/scda.2022")
```
I'll check on my end as well.

**Comment by asbates** [comment]
> @asbates You need to install `scda` and `scda.2022`:
> 
> ```r
> remotes::install_github("insightsengineering/scda")
> remotes::install_github("insightsengineering/scda.2022")
> ```
> 
> I'll check on my end as well.

I have both installed. I'll try to reinstall though.

**Comment by donyunardi** [comment]
Everything looks good.

```r
── R CMD check results ──────────────────────────── teal.osprey 0.1.15 ────
Duration: 1m 39.4s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded
```

```r
── R CMD check results ────────────────────────────── teal.goshawk 0.1.14 ────
Duration: 1m 24.8s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded
```

```r
── R CMD check results ─────────────────────── teal.modules.general 0.2.15 ────
Duration: 6m 16.3s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded
```

```r
── R CMD check results ──────────────────────── teal.modules.clinical 0.8.14 ────
Duration: 4m 9.6s

❯ checking package dependencies ... NOTE
  Imports includes 26 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.

0 errors ✔ | 0 warnings ✔ | 1 note ✖
```

**Comment by donyunardi** [comment]
Since we're reverting the removal of test-get_rcode.R, we have duplicate test cases from `test-get_rcode.R`:
https://github.com/insightsengineering/teal/blob/58bf9ea36666560102db1940cd210e5bc8713078/tests/testthat/test-get_rcode.R#L72-L93

and `test-rcode_utils.R`:
https://github.com/insightsengineering/teal/blob/58bf9ea36666560102db1940cd210e5bc8713078/tests/testthat/test-rcode_utils.R#L47-L68

Should we just delete the test case in `test-get_rcode.R`?
So later on, when the modules are released, we can just delete `test-get_rcode.R` altogether.

**Comment by donyunardi** [comment]
The docs is failing. We also need to revert back update to `_pkgdown.yml` file.
```r
  - title: Deprecated functions
    contents:
      - get_rcode
      - get_rcode_srv
      - get_rcode_ui
      - show_rcode_modal
```

image

**Review by donyunardi — APPROVED** [review]

**Pull request merged**
