### PR TITLE
1303 add a note to `teal_data_module` constructor's vignette

### PR DESCRIPTION
**Pull request by m7pr**
As discussed, the note would be helpful in the `teal_data_module` constructor's vignette https://github.com/insightsengineering/teal/issues/1303
@donyunardi assigning you for the review as you said yesterday you might have a look at this one.

### CODE REVIEW

**Review by donyunardi — CHANGES_REQUESTED** [review]
I understand that `teal_transform_module` is an instance of `teal_data_module`, which is probably why we use the term `teal_data_module` here. However, since the conversations leading up to this PR have been more focused on `teal_transform_module`, it would be better to keep these terms separate. `teal_data_module` should refer to defining delayed data, while `teal_transform_module` is for transforming data within the module. 

Additionally, I think it would be better to include this information in the `data-transform-as-shiny-module.Rmd` vignette, as it relates more directly to the transformation process.

We should also make it clear on what user need to do if they choose to use `eventReactive`. I'm fine with directing user to the discussion link, but we should summarize it clearly for users too.

**Comment by m7pr** [comment]
Hey, I have

- moved the note from `data-as-shiny-module.Rmd` to `data-transform-as-shiny-module.Rmd`
- changed the name from `teal_data_module` into `teal_transform_module`
- specify that `eventReactive` needs to be reactive on `data()` in the `server` part

**Review by donyunardi — APPROVED** [review]
At first, I thought we should show some code if users were to use `eventReactive`. But after thinking it over, if we're discouraging users from doing this, maybe it's best not to mention it at all.

LGTM!

**Comment by gogonzo** [comment]
Issue might be outdated when https://github.com/insightsengineering/teal/pull/1330 goes in

**Review by gogonzo — CHANGES_REQUESTED** [review]
I don't think this is a good way. Please see the comment:

https://github.com/insightsengineering/teal/issues/1303#issuecomment-2355909715

**Comment by m7pr** [comment]
I think we should revisit, once we are done with https://github.com/insightsengineering/teal/pull/1341

**Comment by donyunardi** [comment]
@gogonzo @m7pr can you please assess if we still need this PR?
If not, please close.

**Comment by gogonzo** [comment]
> @gogonzo @m7pr can you please assess if we still need this PR? If not, please close.

[I raised my opinion in the issue](https://github.com/insightsengineering/teal/issues/1303#issuecomment-2355909715), I think more effort on the `teal`'s reactivity is needed before giving up and writing a comment in a vignette.

**Pull request closed without merging**
