### PR TITLE
fix vignette links

### LINKED ISSUE #1106: Links are not working in vignettes
https://github.com/insightsengineering/teal/blob/ebfbb76485fd2a116b98dcc2bac6ed73b9f1e220/vignettes/blueprint/in_app_data.Rmd#L26

The link to `data-as-shiny-module.html` is not working in the `in_app_data` page:
https://insightsengineering.github.io/teal/latest-tag/articles/blueprint/in_app_data.html

The link is currently pointing to:
https://insightsengineering.github.io/teal/latest-tag/articles/blueprint/data-as-shiny-module.html

which leads to 'Page not found' because it's trying to find `data-as-shiny-module.html` under blueprint.

The correct link is: https://insightsengineering.github.io/teal/latest-tag/articles/data-as-shiny-module.html

Similar issues:
https://github.com/insightsengineering/teal/blob/ebfbb76485fd2a116b98dcc2bac6ed73b9f1e220/vignettes/blueprint/intro.Rmd#L37
https://github.com/insightsengineering/teal/blob/ebfbb76485fd2a116b98dcc2bac6ed73b9f1e220/vignettes/blueprint/actors.Rmd#L76

If we're keeping the dynamic path, then we could do `../*.html` for these pages.

### PR DESCRIPTION
**Pull request by donyunardi**
Fixes #1106

### CODE REVIEW

**Review by chlebowa — CHANGES_REQUESTED** [review]
The links fixed here do work properly.

Links that are still 404:

in README:
- https://insightsengineering.github.io/teal/latest-tag/articles/teal.html

in vignettes/adding-support-for-reporting.Rmd:
- https://insightsengineering.github.io/teal.reporter/latest-tag/reference/simple_reporter.html (several instances)

in vignettes/blueprint/intro.Rmd
- https://insightsengineering.github.io/teal/latest-tag/articles/teal.html

----

The `Get Started` menu item is identical to `Articles > Getting Started with teal` - make sure this is deliberate (it may be).

**Comment by donyunardi** [comment]
> in README:
>   - https://insightsengineering.github.io/teal/latest-tag/articles/teal.html

Fixed

> in vignettes/adding-support-for-reporting.Rmd:
> - https://insightsengineering.github.io/teal.reporter/latest-tag/reference/simple_reporter.html (several instances)

I think this has something to do with the cross-reference links issue which was reporter [here](https://github.com/insightsengineering/coredev-tasks/issues/506). Let's move forward for now.

> in vignettes/blueprint/intro.Rmd
>   - https://insightsengineering.github.io/teal/latest-tag/articles/teal.html

I already fixed this. I don't see any other broken links in intro.Rmd

**Comment by donyunardi** [comment]
> I think this has something to do with the cross-reference links issue which was reported https://github.com/insightsengineering/coredev-tasks/issues/506. Let's move forward for now.

@vedhav provided more context and looks like this is a bug. However, this is not a blocker for us to move forward with patch release.

**Review by vedhav — APPROVED** [review]
Checked the links and they work fine 👌🏽

**Pull request merged**
