### PR TITLE
210 substitute `teal.data::get_code` with `teal.code::get_code`

### PR DESCRIPTION
**Pull request by m7pr**
Partner to 
- https://github.com/insightsengineering/teal.data/pull/343 
- https://github.com/insightsengineering/teal.code/pull/214

Replace `teal.data::get_code()` (that worked on `teal_data()`) with `teal.code::get_code()` (that works on `qenv`).

### CODE REVIEW

**Review by gogonzo — CHANGES_REQUESTED** [review]
I'm sceptic about `class(data) <- "qenv"` to force usage of the `teal.code` method. What is the reason? Is it to avoid deprecation warning create `teal.data::get_code`?

**Comment by m7pr** [comment]
@gogonzo `teal.code::get_code` does not have a method for `teal_data`. It has method only for `qenv`. So if you apply `teal.code::get_code` on `teal_data` then a generic is applied. Generic doesn't extract code. So you need to change the class of the obeject to `qenv`

**Comment by gogonzo** [comment]
> @gogonzo teal.code::get_code does not have a method for teal_data. It has method only for qenv

Yes and not.
```r
teal_data() |> inherits("qenv")
# TRUE
```

> Generic doesn't extract code

No, it doesn't. Generic selects a method which matches the `x` class and calls this method - which technically it will pick the `teal.code::get_code()`

**Comment by m7pr** [comment]
My bad! You are right. I got confused. Reverted the change.
Now it's only a change from `teal.data::get_code -> teal.code::get_code`

**Review by gogonzo — APPROVED** [review]
👍

**Comment by gogonzo** [comment]
CI/CD pulls released versions. Probably after replacing staged.dependencies action. 

image

**Pull request merged**
