### PR TITLE
1352 functions in `data` raise warnings

### LINKED ISSUE #1352: [Bug]: functions in `data` raise warnings
### What happened?

When `data` contains a function, a warning is logged when running `init`:

```
[WARN] 2024-09-26 11:08:10.5918 pid:6800 token:[] teal In 'rlang::hash(list(data = data, modules = modules))': 'package:teal' may not be available when loading
```

A similar one is logged when the app is run:
```
[WARN] 2024-09-26 11:48:19.3963 pid:21388 token:[4e453302] teal In 'rlang::hash(data[[dataname]])': 'package:teal' may not be available when loading  
```

It looks like it's happening in `create_app_id`. I [modified the function](https://github.com/insightsengineering/teal/pull/1353) so that `data` is also passed through `defunction` and that removed the warning raised when running `init` but not the one raised when runninng the app.

<details> <summary> example app </summary>

```
devtools::load_all("teal")

options("teal.bs_theme" = bslib::bs_theme(version = "5"))

data <- teal_data() |>
  within(iris <- iris) |>
  within(foo <- function(x) cat("hello\n"))
modules <- modules(
  example_module()
)

app <- init(data = data, modules = modules)

runApp(app)
```

</details>

### sessionInfo()

_No response_

### Relevant log output

```R
> packageVersion("teal")
[1] '0.15.2.9064'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by chlebowa**
Fixes #1352 

One warning is removed by extending the `defunction` call in `create_app_id` to the `data` argument.
The other is removed by applying `defunction` to the contents of data when calculating hashes for the integrity check.

Improved recursion condition in function `defunction`.

### CODE REVIEW

**Comment by chlebowa** [comment]
Some unit tests fail in CI but they pass locally. Do you have any advice for me to reproduce them?

**Comment by chlebowa** [comment]
Tests pass locally now.

**Comment by m7pr** [comment]
I see 58 issues in tests on local when I run tests for below dependencies. Those are the same as appear in GitHub Actions

```r
devtools::test_file('tests/testthat/test-module_teal.R')
```

```r
> packageVersion('teal.slice')
[1] '0.5.1.9011'
> packageVersion('teal.data')
[1] '0.6.0.9010'
> packageVersion('teal') #teal comes from this fork
[1] '0.15.2.9066'
```

**Comment by chlebowa** [comment]
@m7pr I finally found where I messed up, have a look now.

**Review by m7pr — APPROVED** [review]
LGTM

**Review by gogonzo — CHANGES_REQUESTED** [review]
`defunction` is a private function. It can't be exposed in show R code!

**Comment by chlebowa** [comment]
> `defunction` is a private function. It can't be exposed in show R code!

It is not:
```
foo <- function() cat("hi\n")
mtcars <- mtcars
stopifnot(rlang::hash(foo) == "f5343390f4f30d7df3658452ee946a23")
stopifnot(rlang::hash(mtcars) == "d0487363db4e6cc64fdb740cb6617fc0")
.raw_data <- list2env(list(foo = foo, mtcars = mtcars))
lockEnvironment(.raw_data)
```

**Comment by gogonzo** [comment]
> > `defunction` is a private function. It can't be exposed in show R code!
> 
> It is not:
> 
> ```
> foo <- function() cat("hi\n")
> mtcars <- mtcars
> stopifnot(rlang::hash(foo) == "f5343390f4f30d7df3658452ee946a23")
> stopifnot(rlang::hash(mtcars) == "d0487363db4e6cc64fdb740cb6617fc0")
> .raw_data <- list2env(list(foo = foo, mtcars = mtcars))
> lockEnvironment(.raw_data)
> ```

Yup. Is the hash in stopifnot matches `rlang::hash`? Because `rlang::hash` in show-r-code is evaluated on the `foo` while in a `.get_hashes_code` it is on `defunction(foo)`.

**Comment by chlebowa** [comment]
You're right, I didn't actually run the repro code 🤦

**Comment by gogonzo** [comment]
Closing in favour of 
- https://github.com/insightsengineering/teal.slice/pull/624
- https://github.com/insightsengineering/teal/pull/1393

**Pull request closed without merging**
