### PR TITLE
update required version of teal.logger

### LINKED ISSUE #1348: [Bug]: critical bug
### What happened?

I just now installed the latest versions of core packges and cannot run an app.

```
teal_app <- teal::init(
  data = teal.data::teal_data(ADSL = teal.modules.general::rADSL),
  modules = teal::modules(teal.modules.general::tm_missing_data())
)
shiny::runApp(teal_app)
```
```
Loading required package: shiny

Listening on http://127.0.0.1:6848
Browsing http://127.0.0.1:6848    
Warning in module(childScope$input, childScope$output, childScope, ...) :  
  Automatic lockfile creation disabled. `mirai` and `renv` packages must be installed.
Warning: Error in : 'log_shiny_input_changes' is not an exported object from 'namespace:teal.logger'
  1: shiny::runApp
```

```
c("teal.modules.general", "teal.data", "teal.slice", "teal") |> 
  sapply(function(x) as.character(packageVersion(x))) |>
  cbind()
```
```
                     [,1]
teal.modules.general "0.3.0.9049"
teal.data            "0.6.0.9011"
teal.slice           "0.5.1.9012"
teal                 "0.15.2.9064"
```

### sessionInfo()

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by chlebowa**
fixes #1348

### CODE REVIEW

**Review by donyunardi — APPROVED** [review]
Thanks @chlebowa !

**Comment by vedhav** [comment]
Before we merge I just wanted to confirm if this is needed?
The `teal.logger::log_shiny_input_changes` is only used in module packages and `teal` does not use them.
The issue mentioned in this PR originates from the tmg and we already have the min version of `teal.logger (>= 0.2.0.9004)` in tmg which has the function `log_shiny_input_changes` exported.

**Comment by chlebowa** [comment]
Fair point @vedhav, I didn't test with `example_module()`. Perhaps this fix belongs in module packages.

**Review by donyunardi — CHANGES_REQUESTED** [review]
Thanks @vedhav I think you're right. 

The related PR in question is:
https://github.com/insightsengineering/teal.modules.general/pull/760

@chlebowa can you confirm on your end?

**Comment by chlebowa** [comment]
Now that I have the latest `teal.logger` installed, it doesn't matter which package forced it.
However, I'm afraid I will run into the same issue the next time I want to use `tmc`.

**Comment by donyunardi** [comment]
> However, I'm afraid I will run into the same issue the next time I want to use tmc.

In `tmc` we also forced the teal.logger to be `>= 0.2.0.9004`
https://github.com/insightsengineering/teal.modules.clinical/blob/1d4beec4ef14197445191b0957bb38e8bba9196d/DESCRIPTION#L60

Are you also using the latest tmc (from main) when you get the error message?

**Comment by donyunardi** [comment]
> At the moment I am not getting the error emssage even using tmc v0.9.1 but, again, my teal.logger is already updated.

This makes sense because the `teal.logger::log_shiny_input_changes` in `tmc` was implemented after v0.9.1.

However, if you install `tmc` from main branch and you only have `teal.logger` 0.2.0, teal.logger would have been updated (or prompted for an update) since `tmc` requires `teal.logger` to be `>= 0.2.0.9004`.

Regardless, I will close this PR without merging since we already force this when using the teal modules.

**Pull request closed without merging**
