### PR TITLE
1315 fix failed pipelines

### LINKED ISSUE #1315: Fix failed pipeline
https://github.com/pawelru/ie_status?tab=readme-ov-file

### PR DESCRIPTION
**Pull request by m7pr**
Close #1315

### CODE REVIEW

**Comment by m7pr** [comment]
https://github.com/insightsengineering/teal/actions/runs/10633773129

**Comment by donyunardi** [comment]
Thanks for the updat, however, the `Dependency Test - release` and `revdepcheck` are still failing.

[Dependency Test - release](https://github.com/insightsengineering/teal/actions/runs/10635970392/job/29486747478#step:9:521)
```
── Dependency resolution (tree): ──

Error : ! Could not solve package dependencies:
* deps::/tmp/RtmpEICD44/filec34faccae5:
  * Can't install dependency teal.data (> 0.6.0.9007) (>= 0.5.1.9009) (>= 0.3.1.9004)
  * Can't install dependency teal.slice (>= 0.5.1.9009) (>= 0.3.1.9004)
  * Can't install dependency teal.reporter (>= 0.3.1.9004)
── Create lockfile... ──────────────────────────────────────────────────────────
Error : ! Could not solve package dependencies:
* deps::/tmp/RtmpEICD44/filec34faccae5:
  * Can't install dependency teal.data (> 0.6.0.9007) (>= 0.5.1.9009) (>= 0.3.1.9004)
  * Can't install dependency teal.slice (>= 0.5.1.9009) (>= 0.3.1.9004)
  * Can't install dependency teal.reporter (>= 0.3.1.9004)
```

[revdepcheck](https://github.com/insightsengineering/teal/actions/runs/10635970392/job/29486746606#step:9:983)
```
── INSTALL ─────────────────────────────────────────────────────── 2 versions ──
Installing CRAN version of teal
Installing DEV version of teal
Installing 5 packages: parallelly, listenv, globals, renv, future
Error: Failed to install 'teal' from local:
  (converted from warning) installation of package ‘/tmp/RtmpnwIYxk/filebd5cdc1854/teal_0.15.2.9059.tar.gz’ had non-zero exit status
Execution halted
```

Need to find out why there are failing.
@pawelru is something that you can quickly diagnose based on your experience?
Personally, I don't understand why `Dependency Test - release` is failing.

**Comment by m7pr** [comment]
revdepcheck might be fixed after changed in revdepcheck in here https://github.com/insightsengineering/setup-r-dependencies/pull/4

**Comment by m7pr** [comment]
Restared the revdepcheck in here https://github.com/insightsengineering/teal/actions/runs/10666737833

**Comment by m7pr** [comment]
Still something wrong with revdepcheck that I don't understand

**Comment by m7pr** [comment]
restarted the check for R-Hub https://github.com/insightsengineering/teal/actions/runs/11162647649

**Comment by m7pr** [comment]
restarted the check for revdepcheck as well https://github.com/insightsengineering/teal/actions/runs/11162670917

**Comment by donyunardi** [comment]
Restarted the dependency test:
https://github.com/insightsengineering/teal/actions/runs/11172110749/job/31058038805

As expected, max and released pipeline failed because teal depends on DEV version on some of the dependencies.
Everything else looks good.

**Review by donyunardi — APPROVED** [review]

**Comment by donyunardi** [comment]
On second thought, I don't understand why max and released failed. I thought with the implementation of https://github.com/insightsengineering/teal/pull/1361 the workflow will install the dev version of the dependencies?

tagging @m7pr or @pawelru

**Comment by pawelru** [comment]
The referenced changes are generally speaking for everything except verdepcheck which has its own dependency installation logic (based on well... the VERsions of DEPendencies)

**Comment by m7pr** [comment]
Yep, those changes are for other builds, not verdepcheck. Let me explain that during today's DAILY

**Pull request merged**
