### PR TITLE
1154 deprecation for `show_rcode_modal`

### LINKED ISSUE #1154: Remove `teal::show_rcode_modal`
There is an exported `show_rcode_modal` modal in `teal`. 

However if you seek for the usage of `show_rcode_modal` inside the whole organization, 
it only appears in `{teal.devel}` and [design/design_km.Rmd](https://github.com/insightsengineering/teal.modules.hermes/blob/bcea1efe2c2d90c8066b638bd86dd80c16a69512/design/design_km.Rmd#L125) in `{teal.modules.hermes}`. [Search results](https://github.com/search?q=org%3Ainsightsengineering%20show_rcode_modal&type=code)

I think this `modal` was replaced by `teal.widgets::verbatim_popup_ui(ns("rcode"), button_label = "Show R code")`. [Search results](https://github.com/search?q=org%3Ainsightsengineering+verbatim_popup&type=code)

### PR DESCRIPTION
**Pull request by m7pr**
Close #1154

### CODE REVIEW

**Review by gogonzo — APPROVED** [review]

**Review by gogonzo — COMMENTED** [review]
I think `init.js` should be also removed.

**Comment by m7pr** [comment]
For `init.js` I created https://github.com/insightsengineering/teal/issues/1218

**Comment by gogonzo** [comment]
> For `init.js` I created #1218

Sorry my bad, init.js should be removed after hard deprecation. Not now

**Comment by m7pr** [comment]
recheck

**Comment by m7pr** [comment]
> init.js should be removed after hard deprecation. Not now

Yes, that was clear!

**Pull request merged**
